#image: 
#    name: registry.gitlab.com/rosi-ap/rosiap_docker_images:rmf-foxy-nightly

image: docker:git                                          # docker and git clients

services:
  - docker:19.03.5-dind                                    # enable docker-in-docker

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .ccache/
    
before_script:
  #  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master

  - apk add --update bash coreutils tar grep curl           # Install industrial_ci dependencies
  - apk add --update python3 py3-pip python3-dev            # Extra tools needed for coveralls.io
  - git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci/ .industrial_ci -b pr-coverage-rebased

variables:
  TMPDIR: "${CI_PROJECT_DIR}.tmp"
  DOCKER_RUN_OPTS: "-v /etc/ssl/certs:/etc/ssl/certs:ro"
  CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"
  # ===== Code Coverage Services =====
  # === codecov.io ===
  #CODE_COVERAGE: "codecov.io"                  
  #CODECOV_TOKEN: $CODECOV_TOKEN
  # === coveralls.io ===
  CODE_COVERAGE: "coveralls.io"
  COVERALLS_REPO_TOKEN: $COVERALLS_TOKEN

foxy-main:
  variables:
    ROS_DISTRO: "foxy"
    ROS_REPO: "main"
    ISOLATION: "shell"  

  script:
      - .industrial_ci/gitlab.sh
      
foxy-testing:
  variables:
    ROS_DISTRO: "foxy"
    ROS_REPO: "testing"
    ISOLATION: "shell"  

  script:
      - .industrial_ci/gitlab.sh
