language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - CODE_COVERAGE="coveralls.io"			           # Or codecov.io, comment it if not in use
    #- CODECOV_TOKEN=$CODECOV_TOKEN               # For private repo
    - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN     # For private repo
    
  matrix:
    - ROS_DISTRO="foxy" ROS_REPO=testing
    - ROS_DISTRO="foxy" ROS_REPO=main

install:
  #- git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master     # Default
  - git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci/ .industrial_ci -b pr-coverage-rebased  # For code coverage service
  
script:
  - .industrial_ci/travis.sh
