language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - CODE_COVERAGE="coveralls.io"			# Or codecov.io
    # - COVERALLS_REPO_TOKEN=".." # For private repo
    
  matrix:
    - ROS_DISTRO="eloquent" ROS_REPO=testing
    - ROS_DISTRO="eloquent" ROS_REPO=main
    - ROS_DISTRO="foxy" ROS_REPO=testing
    - ROS_DISTRO="foxy" ROS_REPO=main
    
install:
  #-  git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
  - apk add --update bash coreutils tar grep curl           # Install industrial_ci dependencies
  - apk add --update python3 py3-pip python3-dev            # Extra tools needed for coveralls.io
  - git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci/ .industrial_ci -b pr-coverage-rebased
  
script:
  - .industrial_ci/travis.sh
