language: generic
services:
  - docker

env:
  global:
    - PARALLEL_TESTS=true
    - CODE_COVERAGE="codecov.io"

  matrix:
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPO=main
    - ROS_DISTRO="eloquent" ROS_REPO=testing
    - ROS_DISTRO="eloquent" ROS_REPO=main

install:
  -  git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci.git .industrial_ci -b  pr-coverage 
script:
  - .industrial_ci/travis.sh
