language: generic
services:
  - docker
python: "3.6"

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - CODE_COVERAGE=coveralls.io
  matrix:
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPO=main
    - ROS_DISTRO="eloquent" ROS_REPO=testing
    - ROS_DISTRO="eloquent" ROS_REPO=main

install:
  - sudo apt-get install -y python3-setuptools python3-wheel python3-pip python3-dev
  - git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci.git .industrial_ci -b pr-coverage-rebased

before_script:
  - python3 -m pip install --user coveralls

script:
  - .industrial_ci/travis.sh
