name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: eloquent, ROS_REPO: main}
    env:
      CODE_COVERAGE: coveralls.io
      COVERALLS_REPO_TOKEN: Lx2XQw9fenGdTwb2PN39khuRshYml1M54
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'Briancbn/industrial_ci@pr-coverage-rebased'
        env: ${{matrix.env}}
